#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="twilio-hourly-sms"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CREDS_FILE="${SCRIPT_DIR}/twilio_hourly_sms.env"

# Determine install location based on root/user
if [[ "${EUID}" -eq 0 ]]; then
  INSTALL_DIR="/usr/local/bin"
else
  INSTALL_DIR="${HOME}/.local/bin"
fi
SCRIPT_PATH="${INSTALL_DIR}/twilio_hourly_sms.sh"
mkdir -p "${INSTALL_DIR}"

if [[ ! -f "${CREDS_FILE}" ]]; then
  echo "Missing creds file: ${CREDS_FILE}" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "${CREDS_FILE}"
set +a

required_vars=(
  TWILIO_ACCOUNT_SID
  TWILIO_AUTH_TOKEN
  TWILIO_FROM
  TWILIO_TO
)

missing=0
for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "Missing ${var} in ${CREDS_FILE}" >&2
    missing=1
  fi
done

if (( missing )); then
  exit 1
fi

write_twilio_script() {
  {
    printf '%s\n' '#!/usr/bin/env bash'
    printf '\n'
    printf '%s\n' '# This file is generated by install_twilio_hourly_sms_service.sh'
    printf '%s\n' '# Update twilio_hourly_sms.env and re-run install to change credentials.'
    printf 'TWILIO_ACCOUNT_SID=%q\n' "${TWILIO_ACCOUNT_SID}"
    printf 'TWILIO_AUTH_TOKEN=%q\n' "${TWILIO_AUTH_TOKEN}"
    printf 'TWILIO_FROM=%q\n' "${TWILIO_FROM}"
    printf 'TWILIO_TO=%q\n' "${TWILIO_TO}"
    printf '\n'
    cat <<'EOF'
if [[ -z "${TWILIO_ACCOUNT_SID}" || -z "${TWILIO_AUTH_TOKEN}" || -z "${TWILIO_FROM}" || -z "${TWILIO_TO}" ]]; then
  echo "Missing Twilio credentials. Update twilio_hourly_sms.env and re-run install." >&2
  exit 1
fi

while true; do
  body="System running: $(hostname) @ $(date -Is)"
  curl -sS -X POST \
    "https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/Messages.json" \
    --data-urlencode "To=${TWILIO_TO}" \
    --data-urlencode "From=${TWILIO_FROM}" \
    --data-urlencode "Body=${body}" \
    -u "${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}" \
    >/dev/null
  sleep 3600
done
EOF
  } > "${SCRIPT_PATH}"
  chmod +x "${SCRIPT_PATH}"
}

install_user_service() {
  service_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  service_file="${service_dir}/${SERVICE_NAME}.service"
  mkdir -p "${service_dir}"
  cat > "${service_file}" <<EOF
[Unit]
Description=Twilio hourly SMS heartbeat
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=${SCRIPT_PATH}
Restart=always
RestartSec=30

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable --now "${SERVICE_NAME}"
  echo "Installed user service: ${SERVICE_NAME}"
  echo "Manage with: systemctl --user status|stop|start|disable ${SERVICE_NAME}"
}

install_system_service() {
  service_file="/etc/systemd/system/${SERVICE_NAME}.service"
  cat > "${service_file}" <<EOF
[Unit]
Description=Twilio hourly SMS heartbeat
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=${SCRIPT_PATH}
Restart=always
RestartSec=30
User=${SUDO_USER:-$USER}

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now "${SERVICE_NAME}"
  echo "Installed system service: ${SERVICE_NAME}"
  echo "Manage with: systemctl status|stop|start|disable ${SERVICE_NAME}"
}

write_twilio_script

if [[ "${EUID}" -eq 0 ]]; then
  install_system_service
else
  install_user_service
fi
