#!/usr/bin/env bash

# This file is generated by install_twilio_hourly_sms_service.sh
# Update twilio_hourly_sms.env and re-run install to change credentials.
TWILIO_ACCOUNT_SID=''
TWILIO_AUTH_TOKEN=''
TWILIO_FROM=''
TWILIO_TO=''

if [[ -z "${TWILIO_ACCOUNT_SID}" || -z "${TWILIO_AUTH_TOKEN}" || -z "${TWILIO_FROM}" || -z "${TWILIO_TO}" ]]; then
  echo "Missing Twilio credentials. Update twilio_hourly_sms.env and re-run install." >&2
  exit 1
fi

while true; do
  body="System running: $(hostname) @ $(date -Is)"
  curl -sS -X POST \
    "https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/Messages.json" \
    --data-urlencode "To=${TWILIO_TO}" \
    --data-urlencode "From=${TWILIO_FROM}" \
    --data-urlencode "Body=${body}" \
    -u "${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}" \
    >/dev/null
  sleep 3600
done
